#!/bin/bash

clear
#--------@LSVPN-----------#
source ShellBot2.sh
ShellBot.init --token "5361713081:AAHt7V0qVDso6Yf0-wCgJK76ZqQ7DvJJ9x8" --monitor --flush
ShellBot.username

# - Funcao menu
menu() {
    local msg
        msg="=×=×=×=×=×=×=×=×=×=×=×=×=×=\n"
        msg+="<b>🤖 OLA SEJA BEM VINDO(a) 🤖</b>\n"
        msg+="=×=×=×=×=×=×=×=×=×=×=×=×=×=\n\n"
        msg+="Gere seu teste agora mesmo!"
        ShellBot.sendMessage --chat_id ${message_chat_id[$id]} \
        --text "$(echo -e $msg)" \
        --reply_markup "$keyboard1" \
        --parse_mode html
        return 0
}

# - funcao criar ssh
criarteste() {
    if grep -q ${callback_query_from_id} lista; then
        created_date=$(grep -w ${callback_query_from_id} lista | cut -d ' ' -f 2)
        current_date=$(date +%s)
        if (( current_date - created_date > 3 * 24 * 60 * 60 )); then
            sed -i "/${callback_query_from_id}/d" lista
        else
            ShellBot.sendMessage --chat_id ${callback_query_message_chat_id} \
                --text "🚫 Você já gerou um SSH recentemente. 📞 Entre em contato com o administrador."
            return 0
        fi
    fi

    if ! grep -q ${callback_query_from_id} lista; then
        echo "${callback_query_from_id} $(date +%s)" >> lista

        usuario=$(echo teste$(( RANDOM % 99999 )))
        senha=$(( RANDOM % 99999 ))
        limite='1'
        tempo='1'
        tuserdate=$(date '+%C%y/%m/%d' -d " +1 days")
        useradd -M -N -s /bin/false $usuario -e $tuserdate > /dev/null 2>&1
        (echo "$senha"; echo "$senha") | passwd $usuario > /dev/null 2>&1
        echo "$senha" > /etc/SSHPlus/senha/$usuario
        echo "$usuario $limite" >> /root/usuarios.db
        echo "#!/bin/bash
pkill -f "$usuario"
userdel --force $usuario
grep -v ^$usuario[[:space:]] /root/usuarios.db > /tmp/ph ; cat /tmp/ph > /root/usuarios.db
rm /etc/SSHPlus/senha/$usuario > /dev/null 2>&1
rm -rf /etc/SSHPlus/userteste/$usuario.sh" > /etc/SSHPlus/userteste/$usuario.sh
        chmod +x /etc/SSHPlus/userteste/$usuario.sh
        at -f /etc/SSHPlus/userteste/$usuario.sh now + $tempo hour > /dev/null 2>&1
        echo ${callback_query_from_id} >> lista

        # - ENVIA O SSH
        ShellBot.sendMessage --chat_id ${callback_query_message_chat_id} \
            --text "$(echo -e "✅ <b>Criado com sucesso</b> ✅\n\nSERVIDOR: TESTE\nUSUARIO: <code>$usuario</code>\nSENHA: <code>$senha</code>\n\n⏳ Expira em: $tempo Horas")" \
            --parse_mode html
        return 0
    fi
}

comprar() {
	local msg
	msg="=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=\n"
	msg+="       <b>💲MENU DE COMPRA💲</b>\n"
	msg+="=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=\n\n"
	msg+="Escolha o plano:\n"

	# Envia uma notificação em resposta ao botão pressionado.
	ShellBot.answerCallbackQuery --callback_query_id ${callback_query_id[$id]} \
							--text "Comprar Acesso"
	# Envia mensagem
	ShellBot.sendMessage --chat_id ${callback_query_message_chat_id[$id]} \
							--text "$(echo -e $msg)" \
							--reply_markup "$keyboard2" \
							--parse_mode html
							
	# retorno
	return 0
}

lsandroid() {
	local msg
	msg="=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=\n"
	msg+="       <b>💳 PAGAMENTO 💳</b>\n"
	msg+="=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=\n\n"
	msg+="<b>LS ANDROID MENSAL</b>\n"
	msg+="VALOR: 19,99 BRL\n"
	msg+="Período: 30 dias\n"
	msg+="Chave PIX:\n"
	msg+="<b>testenetssh@gmail.com</b>\n"
	msg+="Envie o comprovante:\n"
	
	# Envia uma notificação em resposta ao botão pressionado.
	ShellBot.answerCallbackQuery --callback_query_id ${callback_query_id[$id]} \
							--text "LS ANDROID MENSAL"
							
	# Envia mensagem
	ShellBot.sendMessage --chat_id ${callback_query_message_chat_id[$id]} \
							--text "<b>🟠 LS ANDROID MENSAL 🟠</b>\n" \
							--parse_mode html
	
	# Envia foto
	ShellBot.sendPhoto --chat_id ${callback_query_message_chat_id[$id]} \
							--photo @/etc/pics/lsandroid.png \
							--parse_mode html
	
	# Envia mensagem
	ShellBot.sendMessage --chat_id ${callback_query_message_chat_id[$id]} \
							--text "$(echo -e $msg)" \
							--reply_markup "$keyboard3" \
							--parse_mode html
						
	# retorno
	return 0
}

lsandroidp() {
	local msg
	msg="=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=\n"
	msg+="       <b>💳 PAGAMENTO 💳</b>\n"
	msg+="=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=\n\n"
	msg+="<b>LS ANDROID MENSAL PREMIUM</b>\n"
	msg+="VALOR: 24,99 BRL\n"
	msg+="Período: 30 dias\n"
	msg+="Chave PIX:\n"
	msg+="<b>testenetssh@gmail.com</b>\n"
	msg+="Envie o comprovante:\n"
	
	# Envia uma notificação em resposta ao botão pressionado.
	ShellBot.answerCallbackQuery --callback_query_id ${callback_query_id[$id]} \
							--text "LS ANDROID MENSAL PREMIUM"
	
	# Envia mensagem
	ShellBot.sendMessage --chat_id ${callback_query_message_chat_id[$id]} \
							--text "<b>🟣 LS ANDROID MENSAL PREMIUM 🟣</b>\n" \
							--parse_mode html
	
	# Envia foto
	ShellBot.sendPhoto --chat_id ${callback_query_message_chat_id[$id]} \
							--photo @/etc/pics/lsandroidpremium.png \
							--parse_mode html
	
	# Envia mensagem
	ShellBot.sendMessage --chat_id ${callback_query_message_chat_id[$id]} \
							--text "$(echo -e $msg)" \
							--reply_markup "$keyboard3" \
							--parse_mode html
						
	# retorno
	return 0
}


lsandroidplus() {
	local msg
	msg="=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=\n"
	msg+="       <b>💳 PAGAMENTO 💳</b>\n"
	msg+="=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=\n\n"
	msg+="<b>LS ANDROID MENSAL PLUS</b>\n"
	msg+="VALOR: 24,99 BRL\n"
	msg+="Período: 30 dias\n"
	msg+="Chave PIX:\n"
	msg+="<b>testenetssh@gmail.com</b>\n"
	msg+="Envie o comprovante:\n"
	
	# Envia uma notificação em resposta ao botão pressionado.
	ShellBot.answerCallbackQuery --callback_query_id ${callback_query_id[$id]} \
							--text "LS ANDROID MENSAL PLUS"
	
	# Envia mensagem
	ShellBot.sendMessage --chat_id ${callback_query_message_chat_id[$id]} \
							--text "<b>🔵 LS ANDROID MENSAL PLUS 🔵</b>\n" \
							--parse_mode html
	
	# Envia foto
	ShellBot.sendPhoto --chat_id ${callback_query_message_chat_id[$id]} \
							--photo @/etc/pics/lsandroidpremium.png \
							--parse_mode html
	
	# Envia mensagem
	ShellBot.sendMessage --chat_id ${callback_query_message_chat_id[$id]} \
							--text "$(echo -e $msg)" \
							--reply_markup "$keyboard3" \
							--parse_mode html
						
	# retorno
	return 0
}



lsandroidplusp() {
	local msg
	msg="=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=\n"
	msg+="       <b>💳 PAGAMENTO 💳</b>\n"
	msg+="=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=×=\n\n"
	msg+="<b>LS ANDROID PREMIUM</b>\n"
	msg+="VALOR: 24,99 BRL\n"
	msg+="Período: 30 dias\n"
	msg+="Chave PIX:\n"
	msg+="<b>testenetssh@gmail.com</b>\n"
	msg+="Envie o comprovante:\n"
	
	# Envia uma notificação em resposta ao botão pressionado.
	ShellBot.answerCallbackQuery --callback_query_id ${callback_query_id[$id]} \
							--text "LS ANDROID MENSAL PLUS PREMIUM"
	
	# Envia mensagem
	ShellBot.sendMessage --chat_id ${callback_query_message_chat_id[$id]} \
							--text "<b>🔵🔵 LS ANDROID MENSAL PLUS PREMIUM 🔵🔵</b>\n" \
							--parse_mode html
	
	# Envia foto
	ShellBot.sendPhoto --chat_id ${callback_query_message_chat_id[$id]} \
							--photo @/etc/pics/lsandroidpremium.png \
							--parse_mode html
	
	# Envia mensagem
	ShellBot.sendMessage --chat_id ${callback_query_message_chat_id[$id]} \
							--text "$(echo -e $msg)" \
							--reply_markup "$keyboard3" \
							--parse_mode html
						
	# retorno
	return 0
}

#enviar app
enviarapp() {
    ShellBot.answerCallbackQuery --callback_query_id ${callback_query_id[$id]} \
        --text "♻️ ENVIANDO APLICATIVO, AGUARDE..."
    ShellBot.sendDocument --chat_id ${callback_query_message_chat_id} \
        --document "/etc/app/LSVPN1054apk" \
    return 0
}

#informacoes usuario
infouser () {
	ShellBot.sendMessage --chat_id ${message_chat_id[$id]} \
	--text "$(echo -e "Nome:  ${message_from_first_name[$(ShellBot.ListUpdates)]}\nUser: @${message_from_username[$(ShellBot.ListUpdates)]:-null}")\nID: ${message_from_id[$(ShellBot.ListUpdates)]} " \
	--parse_mode html
	return 0
}

unset botao1
botao1=''
unset botao2
botao2=''
unset botao3
botao3=''
ShellBot.InlineKeyboardButton --button 'botao1' --line 1 --text '♻️ GERAR TESTE ♻️' --callback_data 'gerarssh'
ShellBot.InlineKeyboardButton --button 'botao1' --line 2 --text '📥 BAIXAR APLICATIVO 📥' --callback_data '2' --url 'http://bit.ly/LSVPN1054apk'
ShellBot.InlineKeyboardButton --button 'botao1' --line 3 --text '💲 COMPRAR ACESSO 💲' --callback_data 'compra'
ShellBot.InlineKeyboardButton --button 'botao2' --line 1 --text 'LS ANDROID' --callback_data 'lsand'
ShellBot.InlineKeyboardButton --button 'botao2' --line 1 --text 'LS ANDROID PREMIUM' --callback_data 'lsandp'
ShellBot.InlineKeyboardButton --button 'botao2' --line 2 --text 'LS ANDROID PLUS' --callback_data 'lsandplus'
ShellBot.InlineKeyboardButton --button 'botao2' --line 2 --text 'LS ANDROID PLUS PREMIUM' --callback_data 'lsandplusp'
ShellBot.InlineKeyboardButton --button 'botao2' --line 3 --text '↩️ VOLTAR ' --callback_data 'voltar1'
ShellBot.InlineKeyboardButton --button 'botao3' --line 1 --text '📄 ENVIAR COMPROVANTE 📄' --callback_data '1' --url 'http://bit.ly/LSVPN'
ShellBot.InlineKeyboardButton --button 'botao3' --line 2 --text '↩️ VOLTAR ↩️' --callback_data 'voltar2'

ShellBot.regHandleFunction --function criarteste --callback_data gerarssh
ShellBot.regHandleFunction --function comprar --callback_data compra
ShellBot.regHandleFunction --function lsandroid --callback_data lsand
ShellBot.regHandleFunction --function lsandroidp --callback_data lsandp
ShellBot.regHandleFunction --function lsandroidplus --callback_data lsandplus
ShellBot.regHandleFunction --function lsandroidplusp --callback_data lsandplusp
ShellBot.regHandleFunction --function menu --callback_data voltar1
ShellBot.regHandleFunction --function comprar --callback_data voltar2

unset keyboard1
keyboard1="$(ShellBot.InlineKeyboardMarkup -b 'botao1')"

unset keyboard2
keyboard2="$(ShellBot.InlineKeyboardMarkup -b 'botao2')"

unset keyboard3
keyboard3="$(ShellBot.InlineKeyboardMarkup -b 'botao3')"

while :; do
  ShellBot.getUpdates --limit 100 --offset $(ShellBot.OffsetNext) --timeout 30
  for id in $(ShellBot.ListUpdates); do
    (
      ShellBot.watchHandle --callback_data ${callback_query_data[$id]}
      comando=(${message_text[$id]})
      [[ "${comando[0]}" = "/menu"  || "${comando[0]}" = "/start"|| "${comando[0]}" = "menu" ]] && menu
      [[ "${comando[0]}" = "/id"  ]] && infouser
    ) &
  done
done
